<?php

namespace Database\Seeders;

use App\Models\Mahasiswa;
use Illuminate\Database\Seeder;

class MahasiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'no_pendaftaran' => 'PEN2026001',
                'no_identitas' => '3201010101010001',
                'nama' => 'Ahmad Rizki Pratama',
                'jenis_kelamin' => 'Laki-laki',
                'prodi' => 'Keperawatan',
                'prodi_pilihan_1' => 'Keperawatan',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2005-01-15',
                'asal_sekolah' => 'SMA Negeri 1 Jakarta',
                'alamat' => 'Jl. Merdeka No. 12, Jakarta',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'selesai',
                'status_dokter' => 'selesai',
                'kesimpulan_akhir' => 'memenuhi_syarat',
                'keterangan_kesimpulan' => 'Sehat dan memenuhi syarat',
            ],
            [
                'no_pendaftaran' => 'PEN2026002',
                'no_identitas' => '3201010101010002',
                'nama' => 'Siti Nurhaliza',
                'jenis_kelamin' => 'Perempuan',
                'prodi' => 'Kebidanan',
                'prodi_pilihan_1' => 'Kebidanan',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2004-06-20',
                'asal_sekolah' => 'SMA Negeri 3 Bandung',
                'alamat' => 'Jl. Asia Afrika No. 3, Bandung',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'selesai',
                'status_dokter' => 'selesai',
                'kesimpulan_akhir' => 'tidak_memenuhi_syarat',
                'keterangan_kesimpulan' => 'Butuh tindak lanjut medis',
            ],
            [
                'no_pendaftaran' => 'PEN2026003',
                'no_identitas' => '3201010101010003',
                'nama' => 'Budi Santoso',
                'jenis_kelamin' => 'Laki-laki',
                'prodi' => 'Kesehatan Masyarakat',
                'prodi_pilihan_1' => 'Kesehatan Masyarakat',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2005-03-08',
                'asal_sekolah' => 'SMA Negeri 5 Surabaya',
                'alamat' => 'Jl. Pemuda No. 45, Surabaya',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'selesai',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026004',
                'no_identitas' => '3201010101010004',
                'nama' => 'Rina Kurniawati',
                'jenis_kelamin' => 'Perempuan',
                'prodi' => 'Administrasi Kesehatan',
                'prodi_pilihan_1' => 'Administrasi Kesehatan',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '2004-10-02',
                'asal_sekolah' => 'SMA Negeri 2 Semarang',
                'alamat' => 'Jl. Pandanaran No. 10, Semarang',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'belum',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026005',
                'no_identitas' => '3201010101010005',
                'nama' => 'Dewi Lestari',
                'jenis_kelamin' => 'Perempuan',
                'prodi' => 'Farmasi',
                'prodi_pilihan_1' => 'Farmasi',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '2005-07-11',
                'asal_sekolah' => 'SMA Negeri 8 Yogyakarta',
                'alamat' => 'Jl. Malioboro No. 88, Yogyakarta',
                'status_kehadiran' => 'belum_hadir',
                'status_plp' => 'belum',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026006',
                'no_identitas' => '3201010101010006',
                'nama' => 'Fajar Maulana',
                'jenis_kelamin' => 'Laki-laki',
                'prodi' => 'Keperawatan',
                'prodi_pilihan_1' => 'Keperawatan',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '2004-12-19',
                'asal_sekolah' => 'SMA Negeri 2 Medan',
                'alamat' => 'Jl. Gatot Subroto No. 5, Medan',
                'status_kehadiran' => 'tidak_hadir',
                'status_plp' => 'belum',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => 'Tidak hadir pada jadwal pemeriksaan',
            ],
            [
                'no_pendaftaran' => 'PEN2026007',
                'no_identitas' => '3201010101010007',
                'nama' => 'Putri Ayu',
                'jenis_kelamin' => 'Perempuan',
                'prodi' => 'Kebidanan',
                'prodi_pilihan_1' => 'Kebidanan',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '2005-02-27',
                'asal_sekolah' => 'SMA Negeri 1 Malang',
                'alamat' => 'Jl. Ijen No. 21, Malang',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'selesai',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026008',
                'no_identitas' => '3201010101010008',
                'nama' => 'Rafi Hidayat',
                'jenis_kelamin' => 'Laki-laki',
                'prodi' => 'Kesehatan Masyarakat',
                'prodi_pilihan_1' => 'Kesehatan Masyarakat',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2004-05-03',
                'asal_sekolah' => 'SMA Negeri 10 Makassar',
                'alamat' => 'Jl. Pettarani No. 14, Makassar',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'belum',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026009',
                'no_identitas' => '3201010101010009',
                'nama' => 'Lina Marlina',
                'jenis_kelamin' => 'Perempuan',
                'prodi' => 'Administrasi Kesehatan',
                'prodi_pilihan_1' => 'Administrasi Kesehatan',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '2005-09-17',
                'asal_sekolah' => 'SMA Negeri 4 Palembang',
                'alamat' => 'Jl. Sudirman No. 77, Palembang',
                'status_kehadiran' => 'belum_hadir',
                'status_plp' => 'belum',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026010',
                'no_identitas' => '3201010101010010',
                'nama' => 'Andi Wijaya',
                'jenis_kelamin' => 'Laki-laki',
                'prodi' => 'Farmasi',
                'prodi_pilihan_1' => 'Farmasi',
                'tempat_lahir' => 'Denpasar',
                'tanggal_lahir' => '2004-11-29',
                'asal_sekolah' => 'SMA Negeri 2 Denpasar',
                'alamat' => 'Jl. Teuku Umar No. 8, Denpasar',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'selesai',
                'status_dokter' => 'selesai',
                'kesimpulan_akhir' => 'memenuhi_syarat',
                'keterangan_kesimpulan' => 'Sehat dan memenuhi syarat',
            ],
            [
                'no_pendaftaran' => 'PEN2026011',
                'no_identitas' => '3201010101010011',
                'nama' => 'Nadia Salsabila',
                'jenis_kelamin' => 'Perempuan',
                'prodi' => 'Keperawatan',
                'prodi_pilihan_1' => 'Keperawatan',
                'tempat_lahir' => 'Padang',
                'tanggal_lahir' => '2005-04-07',
                'asal_sekolah' => 'SMA Negeri 7 Padang',
                'alamat' => 'Jl. Khatib Sulaiman No. 11, Padang',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'selesai',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026012',
                'no_identitas' => '3201010101010012',
                'nama' => 'Rizal Fahmi',
                'jenis_kelamin' => 'Laki-laki',
                'prodi' => 'Kesehatan Masyarakat',
                'prodi_pilihan_1' => 'Kesehatan Masyarakat',
                'tempat_lahir' => 'Balikpapan',
                'tanggal_lahir' => '2004-08-24',
                'asal_sekolah' => 'SMA Negeri 1 Balikpapan',
                'alamat' => 'Jl. MT Haryono No. 9, Balikpapan',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'belum',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026013',
                'no_identitas' => '3201010101010013',
                'nama' => 'Winda Prameswari',
                'jenis_kelamin' => 'Perempuan',
                'prodi' => 'Administrasi Kesehatan',
                'prodi_pilihan_1' => 'Administrasi Kesehatan',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '2005-12-02',
                'asal_sekolah' => 'SMA Negeri 2 Bogor',
                'alamat' => 'Jl. Pajajaran No. 26, Bogor',
                'status_kehadiran' => 'belum_hadir',
                'status_plp' => 'belum',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026014',
                'no_identitas' => '3201010101010014',
                'nama' => 'Yusuf Ramadhan',
                'jenis_kelamin' => 'Laki-laki',
                'prodi' => 'Farmasi',
                'prodi_pilihan_1' => 'Farmasi',
                'tempat_lahir' => 'Banjarmasin',
                'tanggal_lahir' => '2004-09-30',
                'asal_sekolah' => 'SMA Negeri 3 Banjarmasin',
                'alamat' => 'Jl. A. Yani No. 15, Banjarmasin',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'selesai',
                'status_dokter' => 'selesai',
                'kesimpulan_akhir' => 'memenuhi_syarat',
                'keterangan_kesimpulan' => 'Sehat dan memenuhi syarat',
            ],
            [
                'no_pendaftaran' => 'PEN2026015',
                'no_identitas' => '3201010101010015',
                'nama' => 'Aulia Rahman',
                'jenis_kelamin' => 'Laki-laki',
                'prodi' => 'Keperawatan',
                'prodi_pilihan_1' => 'Keperawatan',
                'tempat_lahir' => 'Pekanbaru',
                'tanggal_lahir' => '2005-02-12',
                'asal_sekolah' => 'SMA Negeri 4 Pekanbaru',
                'alamat' => 'Jl. Sudirman No. 18, Pekanbaru',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'belum',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026016',
                'no_identitas' => '3201010101010016',
                'nama' => 'Maya Lestari',
                'jenis_kelamin' => 'Perempuan',
                'prodi' => 'Kebidanan',
                'prodi_pilihan_1' => 'Kebidanan',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '2005-05-14',
                'asal_sekolah' => 'SMA Negeri 6 Cirebon',
                'alamat' => 'Jl. Siliwangi No. 9, Cirebon',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'selesai',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026017',
                'no_identitas' => '3201010101010017',
                'nama' => 'Raka Prasetya',
                'jenis_kelamin' => 'Laki-laki',
                'prodi' => 'Farmasi',
                'prodi_pilihan_1' => 'Farmasi',
                'tempat_lahir' => 'Solo',
                'tanggal_lahir' => '2004-07-22',
                'asal_sekolah' => 'SMA Negeri 1 Surakarta',
                'alamat' => 'Jl. Slamet Riyadi No. 31, Solo',
                'status_kehadiran' => 'belum_hadir',
                'status_plp' => 'belum',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026018',
                'no_identitas' => '3201010101010018',
                'nama' => 'Intan Permata',
                'jenis_kelamin' => 'Perempuan',
                'prodi' => 'Administrasi Kesehatan',
                'prodi_pilihan_1' => 'Administrasi Kesehatan',
                'tempat_lahir' => 'Tasikmalaya',
                'tanggal_lahir' => '2005-01-30',
                'asal_sekolah' => 'SMA Negeri 2 Tasikmalaya',
                'alamat' => 'Jl. Sutisna Senjaya No. 4, Tasikmalaya',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'belum',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026019',
                'no_identitas' => '3201010101010019',
                'nama' => 'Galih Saputra',
                'jenis_kelamin' => 'Laki-laki',
                'prodi' => 'Kesehatan Masyarakat',
                'prodi_pilihan_1' => 'Kesehatan Masyarakat',
                'tempat_lahir' => 'Pontianak',
                'tanggal_lahir' => '2004-03-11',
                'asal_sekolah' => 'SMA Negeri 3 Pontianak',
                'alamat' => 'Jl. Gajah Mada No. 22, Pontianak',
                'status_kehadiran' => 'tidak_hadir',
                'status_plp' => 'belum',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => 'Tidak hadir pada jadwal pemeriksaan',
            ],
            [
                'no_pendaftaran' => 'PEN2026020',
                'no_identitas' => '3201010101010020',
                'nama' => 'Salsa Maharani',
                'jenis_kelamin' => 'Perempuan',
                'prodi' => 'Keperawatan',
                'prodi_pilihan_1' => 'Keperawatan',
                'tempat_lahir' => 'Mataram',
                'tanggal_lahir' => '2005-06-18',
                'asal_sekolah' => 'SMA Negeri 1 Mataram',
                'alamat' => 'Jl. Pejanggik No. 7, Mataram',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'selesai',
                'status_dokter' => 'selesai',
                'kesimpulan_akhir' => 'memenuhi_syarat',
                'keterangan_kesimpulan' => 'Sehat dan memenuhi syarat',
            ],
            [
                'no_pendaftaran' => 'PEN2026021',
                'no_identitas' => '3201010101010021',
                'nama' => 'Dian Pratama',
                'jenis_kelamin' => 'Laki-laki',
                'prodi' => 'Farmasi',
                'prodi_pilihan_1' => 'Farmasi',
                'tempat_lahir' => 'Manado',
                'tanggal_lahir' => '2004-02-05',
                'asal_sekolah' => 'SMA Negeri 2 Manado',
                'alamat' => 'Jl. Sam Ratulangi No. 19, Manado',
                'status_kehadiran' => 'belum_hadir',
                'status_plp' => 'belum',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026022',
                'no_identitas' => '3201010101010022',
                'nama' => 'Riska Anjani',
                'jenis_kelamin' => 'Perempuan',
                'prodi' => 'Administrasi Kesehatan',
                'prodi_pilihan_1' => 'Administrasi Kesehatan',
                'tempat_lahir' => 'Jambi',
                'tanggal_lahir' => '2005-08-09',
                'asal_sekolah' => 'SMA Negeri 5 Jambi',
                'alamat' => 'Jl. Hayam Wuruk No. 6, Jambi',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'belum',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026023',
                'no_identitas' => '3201010101010023',
                'nama' => 'Kurnia Sari',
                'jenis_kelamin' => 'Perempuan',
                'prodi' => 'Kebidanan',
                'prodi_pilihan_1' => 'Kebidanan',
                'tempat_lahir' => 'Kupang',
                'tanggal_lahir' => '2004-12-27',
                'asal_sekolah' => 'SMA Negeri 1 Kupang',
                'alamat' => 'Jl. El Tari No. 16, Kupang',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'belum',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026024',
                'no_identitas' => '3201010101010024',
                'nama' => 'Hendri Saputro',
                'jenis_kelamin' => 'Laki-laki',
                'prodi' => 'Kesehatan Masyarakat',
                'prodi_pilihan_1' => 'Kesehatan Masyarakat',
                'tempat_lahir' => 'Palu',
                'tanggal_lahir' => '2005-09-05',
                'asal_sekolah' => 'SMA Negeri 4 Palu',
                'alamat' => 'Jl. Moh. Yamin No. 12, Palu',
                'status_kehadiran' => 'hadir',
                'status_plp' => 'selesai',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
            [
                'no_pendaftaran' => 'PEN2026025',
                'no_identitas' => '3201010101010025',
                'nama' => 'Taufik Hidayat',
                'jenis_kelamin' => 'Laki-laki',
                'prodi' => 'Farmasi',
                'prodi_pilihan_1' => 'Farmasi',
                'tempat_lahir' => 'Banda Aceh',
                'tanggal_lahir' => '2004-06-01',
                'asal_sekolah' => 'SMA Negeri 2 Banda Aceh',
                'alamat' => 'Jl. Teuku Umar No. 20, Banda Aceh',
                'status_kehadiran' => 'belum_hadir',
                'status_plp' => 'belum',
                'status_dokter' => 'belum',
                'kesimpulan_akhir' => '-',
                'keterangan_kesimpulan' => null,
            ],
        ];

        foreach ($data as $row) {
            Mahasiswa::updateOrCreate(
                ['no_pendaftaran' => $row['no_pendaftaran']],
                $row
            );
        }

        $this->command->info('✓ Mahasiswa seeded: ' . count($data) . ' records');
    }
}
